version: '3.3'
services:

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
      - ../frontend/build/media:/app/result_build/media/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../frontend/build/media:/usr/share/nginx/html/media/

  db:
    container_name: foodgram-db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=foodgram
      - POSTGRES_USER=foodgram_user
      - POSTGRES_PASSWORD=foodgram_password
    env_file:
      - ../backend/.env

  backend:
    container_name: foodgram-backend
    build: ../backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend/:/app/
      - ../frontend/build/media:/app/media/
      - static:/app/static/
      - ../data:/app/data
    depends_on:
      - db
    env_file:
      - ../backend/.env

volumes:
  postgres_data:
  static:
