# Generated by Django 3.2.25 on 2025-05-28 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
        migrations.AddField(
            model_name='purchaselist',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_lists', to='recipes.dish', verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='purchaselist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_lists', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='dishproduct',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.dish', verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='dishproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='dish',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AddField(
            model_name='dish',
            name='products',
            field=models.ManyToManyField(related_name='dishes', through='recipes.DishProduct', to='recipes.Product', verbose_name='Продукты блюда'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='recipes.dish', verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('author')), _negated=True), name='prevent_self_subscription'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaselist',
            unique_together={('user', 'dish')},
        ),
        migrations.AlterUniqueTogether(
            name='dishproduct',
            unique_together={('dish', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'dish')},
        ),
    ]
