# Generated by Django 4.2.22 on 2025-06-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_favorite_shoppingcart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='creator',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='cook_time',
            new_name='cooking_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
