# Generated by Django 4.2.22 on 2025-06-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_quantity_recipeingredient_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='amount',
            new_name='quantity',
        ),
    ]
