# Generated by Django 4.2.22 on 2025-06-06 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_amount_recipeingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество — 1'), django.core.validators.MaxValueValidator(32000, message='Максимальное количество — 32000')], verbose_name='Количество'),
        ),
    ]
