# Generated by Django 4.2.21 on 2025-06-04 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cook_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное время приготовления — 1 минута'), django.core.validators.MaxValueValidator(32000, message='Максимальное время приготовления — 32000 минут')], verbose_name='Время приготовления (мин)'),
        ),
        migrations.AlterField(
            model_name='dishproduct',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество — 1'), django.core.validators.MaxValueValidator(32000, message='Максимальное количество — 32000')], verbose_name='Количество'),
        ),
    ]
