# Generated by Django 4.2.22 on 2025-06-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE recipes_ingredient ALTER COLUMN name TYPE VARCHAR(200) COLLATE "C";',
            reverse_sql='ALTER TABLE recipes_ingredient ALTER COLUMN name TYPE VARCHAR(200);'
        ),
        migrations.RunSQL(
            sql='ALTER TABLE recipes_recipe ALTER COLUMN name TYPE VARCHAR(200) COLLATE "C";',
            reverse_sql='ALTER TABLE recipes_recipe ALTER COLUMN name TYPE VARCHAR(200);'
        ),
    ]
